language: node_js
node_js:
- "stable"
cache:
  directories:
  - node_modules
script:
- yarn run build
- yarn test a
- cypress install
- yarn start and wait-on http://localhost:3000
- yarn cypress run
      
